<center>
    <img src="../imagens/logo_APL.png" width="300" alt="APL logo"  />
</center>

# Bibliotecas `Python`: Introdução ao `Numpy` (Operações em 2D)

**Bem-vindo!** 
Neste material vamos apresentar conceitos básicos da biblioteca `Numpy`, especialmente funções para se trabalhar com computação numérica em **vetores bidimensionais**. Ao final desse módulo espera-se que você seja capaz de entender e realizar operações básicas com `Numpy` em matrizes.

<h2>Conteúdo</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>Criando uma Matriz numérica (ou *Numpy Array* 2D)</li>
        <li>Accessando diferentes elementos em um *Numpy Array* 2D</li>
        <li>Operações básicas</li>
    </ul>
</div>
<hr>

# Criando uma Matriz (*Numpy Array* 2D)  

In [1]:
# Importe as bibliotecas

import numpy as np 

Considere a lista <code> a</code>, a lista contém três listas aninhadas ** cada uma de tamanho igual**.

In [2]:
# Crie uma lista

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

Podemos converter a lista para um Numpy Array da seguinte forma

In [3]:
# Converter lista para uma matriz numpy
# Cada elemento é do mesmo tipo

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

<hr>

<h2 id="access">Acessando diferentes elementos de uma Matriz Numpy</h2>

Podemos usar colchetes retangulares para acessar os diferentes elementos do array. A correspondência entre os colchetes retangulares e a lista e a representação retangular é mostrada na figura a seguir para uma matriz 3x3:

<img src="../imagens/NumTwoEg.png" width="500" />

Podemos acessar a coluna da 2ª linha, 3ª, conforme mostrado na figura a seguir:

<img src="../imagens/NumTwoFT.png" width="400" />

Simplesmente usamos os colchetes e os índices correspondentes ao elemento que gostaríamos:

In [4]:
# Acesse o elemento na segunda linha e terceira coluna

A[1, 2]

23

Também podemos usar a seguinte notação para obter os elementos:

In [5]:
# Acesse o elemento na segunda linha e terceira coluna

A[1][2]

23

Também podemos usar o corte em matrizes numpy. Considere a seguinte figura. Gostaríamos de obter as duas primeiras colunas da primeira linha

<img src="../imagens/NumTwoFSF.png" width="400" />

Isso pode ser feito com a seguinte sintaxe

In [6]:
# Acesse o elemento na primeira linha e na primeira e segunda colunas

A[0][0:2]

array([11, 12])

<hr>

<h2 id="op">Operações básicas</h2>

Também podemos adicionar matrizes. O processo é idêntico ao da adição de matriz. A adição da matriz de <code> X </code> e <code> Y </code> é mostrada na figura a seguir:

<img src="../imagens/NumTwoAdd.png" width="500" />

In [7]:
# Crie as matrizes numpy

X = np.array([[1, 0], [0, 1]]) 
X
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

Podemos adicionar as matrizes numpy da seguinte maneira.

In [8]:
# Somar X e Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Multiplicar um numpy array por um escalar é idêntico a multiplicar uma matriz por um escalar. Se multiplicarmos a matriz <code> Y </code> por 2, simplesmente multiplicamos cada elemento na matriz por 2, conforme mostrado na figura.

<img src="../imagens/NumTwoDb.png" width="500" />

Podemos realizar a mesma operação em numpy da seguinte maneira

In [9]:
# Crie a matriz numpy Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [10]:
# Multiplica Y por 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

A multiplicação de duas matrizes corresponde a um produto elemento-sábio ou produto Hadamard. Considere a matriz <code> X </code> e <code> Y</code>. O produto Hadamard corresponde à multiplicação de cada um dos elementos na mesma posição, ou seja, a multiplicação dos elementos contidos nas mesmas caixas de cores. O resultado é uma nova matriz do mesmo tamanho que a matriz <code> Y </code> ou <code> X</code>, conforme mostrado na figura a seguir.

<img src="../imagens/NumTwoMul.png" width="500" />

Podemos realizar o produto por elemento da matriz <code> X </code> e <code> Y </code> da seguinte maneira:

In [11]:
# Crie a matriz numpy Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [12]:
# Crie a matriz numpy X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [13]:
# Multiplica X por Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

Também podemos realizar a multiplicação da matriz com as matrizes numpy <code> A </code> e <code> B </code> da seguinte maneira:

In [14]:
# Crie a matriz numpy A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [15]:
# Crie a matriz numpy B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

Usamos a função numpy <code> dot </code> para multiplicar as matrizes.

In [16]:
# Calcula o produto interno

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

Usamos o atributo numpy <code> T </code> para calcular a matriz transposta

In [17]:
# Crie a matriz numpy C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [18]:
# Obtem a transposta de C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

<hr>

## Direitos Autorais

[APL Data Intelligence](https://linktr.ee/APLdataintelligence)&#8482;  2021. Este notebook Python e seu código fonte estão liberados sob os termos da [Licença do MIT](https://bigdatauniversity.com/mit-license/).