<center>
    <img src="../imagens/logo_APL.png" width="300" alt="APL logo"  />
</center>

# Bibliotecas `Python`: Introdução ao `Numpy` (Operações em 1D)

**Bem-vindo!** 
Neste material vamos apresentar conceitos básicos da biblioteca `Numpy`, especialmente funções para se trabalhar com computação numérica em **vetores unidimensionais**. Ao final desse módulo espera-se que você seja capaz de entender e realizar operações básicas com `Numpy`.

<h2>Conteúdo</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>
            Introdução:
           <ul>
                <li>Preparação - importando as bibliotecas </li>
                <li>Relembrando - Listas</li>
            </ul>
        </li>
        <li>
            O que é Numpy?
            <ul>
                <li>Tipos</li>
                <li>Atribuir valores</li>
                <li>Cortando</li>
                <li>Atribuir valores com Listas</li>
                <li>Outros atributos</li>
            </ul>
        </li>
        <li>
            Operações com Numpy Array
            <ul>
                <li>Adição com Array</li>
                <li>Multiplicação por escalar</li>
                <li>Multiplicação de dois Numpy Arrays</li>
                <li>Produto escalar</li>
                <li>Somando uma constante a um Numpy Array</li>
            </ul>
        </li>
        <li>Funções matemáticas</li>
        <li>Comando Linspace</li>
    </ul>
</div>

<hr>

# Introdução

`Numpy` é uma biblioteca para computação científica. Possui um conjunto amplo e variado de funções úteis. E, ainda, diversas outras vantagens, como acesso eficiente à memória, por exemplo. Neste notebook vamos trabalhar com vetores unidimensionais (*arrays* 1D).

## Preparação

In [1]:
# Importando as Bibliotecas

import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline  

In [2]:
# Funções para Desenho dos Gráficos

def Plotvec1(u, z, v):
    
    ax = plt.axes()
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)
    plt.text(*(u + 0.1), 'u')
    
    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)
    plt.text(*(v + 0.1), 'v')
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)
    plt.text(*(z + 0.1), 'z')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

## Relembrando - Listas
Crie uma lista Python da seguinte maneira:

In [3]:
# Crie uma lista

a = ["0", 1, "two", "3", 4]

Podemos acessar os dados por meio de um índice:

<img src="../imagens/NumOneList.png" width="660" />

Podemos acessar cada elemento usando um colchete da seguinte maneira:

In [4]:
# Escreva cada elemento

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


<hr>

# O que é `Numpy`?

Uma matriz numpy é semelhante a uma lista. Geralmente é de tamanho fixo e cada elemento é do mesmo tipo. Podemos lançar uma lista em uma matriz numpy importando primeiro numpy:

In [5]:
# importe a biblioteca numpy

import numpy as np 

Em seguida, transformamos uma lista da seguinte maneira:

In [6]:
# Crie um numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

Cada elemento é do mesmo tipo, neste caso, inteiros:

<img src="../imagens/NumOneNp.png" width="500" />

Tal como acontece com as listas, podemos acessar cada elemento por meio de um colchete:

In [7]:
# Escreva cada elemento

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


<h3 id="type">Tipos</h3>

Se verificarmos o tipo do array, obteremos <b> numpy.ndarray</b>:

In [8]:
# Verificar o tipo do array

type(a)

numpy.ndarray

Como as matrizes numpy contêm dados do mesmo tipo, podemos usar o atributo "dtype" para obter o tipo de dados dos elementos da matriz. Neste caso, um número inteiro de 64 bits:

In [ ]:
# Verifique o tipo dos valores armazenados no numpy array

a.dtype

Podemos criar um numpy array com números reais:

In [ ]:
# Crie um numpy array

b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

Quando verificamos o tipo do array, obtemos <b> numpy.ndarray</b>:

In [ ]:
# Verificar o tipo do array

type(b)

Se examinarmos o atributo <code> dtype</code>, vemos o float 64, já que os elementos não são inteiros:

In [ ]:
# Verifique o tipo dos valores armazenados no numpy array

b.dtype

<h3 id="val">Atribuir valores</h3>

Podemos alterar o valor do array, considere o array <code> c</code>:

In [17]:
# Crie um numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

Podemos alterar o primeiro elemento do array para 100 da seguinte maneira:

In [18]:
# Atribua 100 ao primeiro elemento

c[0] = 100
c

array([100,   1,   2,   3,   4])

Podemos alterar o quinto elemento do array para 0 da seguinte maneira:

In [19]:
# Atribua 0 ao quinto elemento

c[4] = 0
c

array([100,   1,   2,   3,   0])

<h3 id="slice">Cortando</h3>

Como as listas, podemos dividir o numpy array e podemos selecionar os elementos de 1 a 3 e atribuí-la a um novo numpy array <code> d </code> da seguinte maneira:

In [20]:
# Cortando o numpy array

d = c[1:4]
d

array([1, 2, 3])

Podemos atribuir os índices correspondentes a novos valores da seguinte maneira:

In [21]:
# Defina o quarto elemento e o quinto elemento para 300 e 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

<h3 id="list">Atribuir valores com Listas</h3>

Da mesma forma, podemos usar uma lista para selecionar um índice específico.
A lista 'select' contém vários valores:


In [ ]:
# Crie uma lista de índices

select = [0, 2, 3]

Podemos usar a lista como um argumento entre colchetes. A saída são os elementos correspondentes ao índice específico:

In [ ]:
# Use uma lista para selecionar elementos

d = c[select]
d

Podemos atribuir os elementos especificados a um novo valor. Por exemplo, podemos atribuir os valores a 100000 da seguinte maneira:

In [ ]:
# Atribuir os elementos especificados a um novo valor

c[select] = 100000
c

<h3 id="other">Outros atributos</h3>

Vamos revisar alguns atributos básicos do array usando o array <code>a</code>:

In [12]:
# Crie um numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

O atributo <code> size </code> é o número de elementos na matriz:

In [13]:
# Obtem o tamanho do numpy array

a.size

5

Os próximos dois atributos farão mais sentido quando chegarmos a dimensões superiores, mas vamos revisá-los. 

O atributo <code> ndim </code> representa o número de dimensões do array ou a classificação do array, neste caso, um:

In [15]:
# Obtem o número de dimensões do numpy array

a.ndim

1

O atributo <code> shape </code> é uma tupla de inteiros indicando o tamanho do array em cada dimensão:

In [16]:
# Obtem o tamanho em cada dimensões do numpy array

a.shape

(5,)

<hr>

<h2 id="op">Operações com Numpy Array</h2>

<h3 id="add">Adição com Arrays</h3>

Considere o numpy array <code>u</code>:

In [22]:
u = np.array([1, 0])
u

array([1, 0])

Considere o numpy array <code>v</code>:

In [23]:
v = np.array([0, 1])
v

array([0, 1])

Podemos adicionar os dois arrays e atribuí-los a z:

In [24]:
# Adição de Numpy Array

z = u + v
z

array([1, 1])

<h3 id="multi">Multiplicação por escalar</h3>

Considere o numpy array <code>y</code>:

In [25]:
# Crie um numpy array

y = np.array([1, 2])
y

array([1, 2])

Podemos multiplicar cada elemento do array por 2:

In [26]:
# Multiplicação no Numpy Array

z = 2 * y
z

array([2, 4])

<h3 id="prod">Multiplicação de dois Numpy Arrays</h3>

Considere o numpy array <code>u</code>:

In [28]:
# Crie um numpy array

u = np.array([1, 2])
u

array([1, 2])

Considere o numpy array <code>v</code>:

In [29]:
# Crie um numpy array

v = np.array([3, 2])
v

array([3, 2])

O produto dos dois numpy array <code> u </code> e <code> v </code> é dado por:

In [30]:
# Calcula o produto de dois numpy arrays

z = u * v
z

array([3, 4])

<h3 id="dot">Produto escalar</h3>

O produto escalar de dois numpy array <code> u </code> e <code> v </code> é dado por:

In [33]:
# Calcula o produto interno
v = np.array([3, 1])
np.dot(u, v)

5

### Somando uma constante a um Numpy Array

Considere o seguinte numpy array:

In [34]:
# Crie um numpy array

u = np.array([1, 2, 3, -1]) 
u

array([ 1,  2,  3, -1])

Adicionando a constante 1 a cada elemento do array:

In [35]:
# Soma 1 a cada elemento do array

u + 1

array([2, 3, 4, 0])

O processo é resumido na seguinte animação:

<img src="../imagens/NumOneAdd.gif" width="500" />

<hr>

## Funções Matemáticas

Crie um numpy array `a`:

In [49]:
a = np.array([1, -1, 1, -1])
a

array([ 1, -1,  1, -1])

Calculando a **média** de um numpy array, usando o método `mean()`.

In [42]:
mean = a.mean()
mean

0.0

Calculando o **desvio padrão** de um numpy array, usando o método `std()`.

In [43]:
standard_deviation=a.std()
standard_deviation

1.0

Crie um numpy array `b`:

In [50]:
# Crie um numpy array
b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

Calculando o **valor máximo** de um numpy array, usando o método `max()`.

In [51]:
max_b = b.max()
max_b

5

Calculando o **valor mínimo** de um numpy array

In [39]:
# Obtem o valor mínimo do numpy array

min_b = b.min()
min_b

-1

### Constantes matemáticas

Podemos acessar o valor de pi em numpy da seguinte maneira:

In [52]:
# Acessando o valor de pi

np.pi

3.141592653589793

Podemos criar o seguinte numpy array em radianos:

In [53]:
# Criando um numpy array em radianos

x = np.array([0, np.pi/2 , np.pi])

Podemos aplicar a função <code> sin </code> ao array <code> x </code> e atribuir os valores ao array <code> y</code>; isso aplica a função seno a cada elemento do array:

In [54]:
# Aplica a função seno em cada elemento

y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

<hr>

## Direitos Autorais

[APL Data Intelligence](https://linktr.ee/APLdataintelligence)&#8482;  2021. Este notebook Python e seu código fonte estão liberados sob os termos da [Licença do MIT](https://bigdatauniversity.com/mit-license/).